# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            RoBO
tagline:          Robust Bayesian Optimization
description:      RoBO is a flexible framework for robust Bayesian Optimization.
url:              http://automl.github.io/
baseurl:          /RoBO/

author:
  name:           'Aaron Klein, Numair Mansur'
  url:            http://automl.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/automl/RoBO
